version: '3.9'

services:
  db:
    container_name: Lunch-Postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Lunch123
      POSTGRES_DB: attendance
    volumes:
      - lunch-data:/var/lib/postgresql/data

volumes:
  lunch-data: